#!/bin/bash

if [ -z "$(pgrep trayer)" ] ; then
    trayer --edge top --align right --SetDockType true --SetPartialStrut true  --expand true --width 10 --transparent true --tint 0x191970 --height 18 &
fi

if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet &
fi

if [ -z "$(pgrep gnome-power-manager)" ] ; then
    gnome-power-manager &
fi

if [ -z "$(pgrep btsync)" ] ; then
    btsync start
fi
